AWSTemplateFormatVersion: '2010-09-09'
Description: EWF - Infra Codepipeline for Cloudformation

## ############################################################################
## This file defines a code pipeline workflow to create a cloudformation stack
## based on the template that is created in the repository. It requires the 
## "ewf-lab-context" stack from lab-1.
##
## Version : 1.0.0
## Date    : 21-05-2019
## Author  : Patricio Téllez (ptellez@amazon.com)
## ############################################################################

## ############################################################################
## Resources
## ############################################################################
Resources:

  ## ##########################################################################
  ## Resources - Repositories
  ## ##########################################################################
  # Infrastructure code repository
  EwfInfraRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: EwfInfraRepo
      RepositoryDescription: Git Repository for application sources
  

  ## ##########################################################################
  ## Resources - Service Roles
  ## ##########################################################################
  # Service Role
  EwfBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
              - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
  
  # Code Pipeline Role
  EwfPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - cloudformation.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AWS-CodePipeline-Service-3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'codecommit:CancelUploadArchive'
                  - 'codecommit:GetBranch'
                  - 'codecommit:GetCommit'
                  - 'codecommit:GetUploadArchiveStatus'
                  - 'codecommit:UploadArchive'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'codedeploy:CreateDeployment'
                  - 'codedeploy:GetApplicationRevision'
                  - 'codedeploy:GetDeployment'
                  - 'codedeploy:GetDeploymentConfig'
                  - 'codedeploy:RegisterApplicationRevision'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'codebuild:BatchGetBuilds'
                  - 'codebuild:StartBuild'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'devicefarm:ListProjects'
                  - 'devicefarm:ListDevicePools'
                  - 'devicefarm:GetRun'
                  - 'devicefarm:GetUpload'
                  - 'devicefarm:CreateUpload'
                  - 'devicefarm:ScheduleRun'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                  - 'lambda:ListFunctions'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'elasticbeanstalk:*'
                  - 'ec2:*'
                  - 'elasticloadbalancing:*'
                  - 'autoscaling:*'
                  - 'cloudwatch:*'
                  - 's3:*'
                  - 'sns:*'
                  - 'cloudformation:*'
                  - 'rds:*'
                  - 'sqs:*'
                  - 'ecs:*'
                  - 'iam:*'
                Resource: '*'

  # Cloudwatch event role
  EwfInfraCloudWatchEventRole:
    Type: AWS::IAM::Role
    DependsOn: EwfInfraWebAppEvoPipeline
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: ewf-cwe-infra-pipeline-execution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource: !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':ewf-webappevo-infra-codepipeline' ] ] 


  ## ##########################################################################
  ## Resources - Code Pipeline
  ## ##########################################################################
  # Ref: https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#actions-valid-providers
  EwfInfraWebAppEvoPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: ewf-webappevo-infra-codepipeline
      RoleArn: !GetAtt EwfPipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Checkout
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                BranchName: master
                RepositoryName: EwfInfraRepo
                PollForSourceChanges: false
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: CreateInfrastructure
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: webappevo-infra-stack
                TemplatePath: SourceOutput::cf-lab-webappevo-infra.yaml
                TemplateConfiguration: SourceOutput::cf-lab-webappevo-infra-config.json
                RoleArn: !GetAtt EwfPipelineRole.Arn
              RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: !ImportValue EwfS3CodePipelineBucket

  ## ##########################################################################
  ## Resources - Cloudwatch Events
  ## ##########################################################################
  # Cloudwatch Events - Infrastructure
  EwfInfraCloudWatchEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: ewf-infra-update
      Description: Event rule that updates the infrastructure based on a cloudformation template
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - 'CodeCommit Repository State Change'
        resources:
          - !Join [ '', [ 'arn:aws:codecommit:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':EwfInfraRepo' ] ]
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - master
      Targets:
        -
          Arn: 
            !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':ewf-webappevo-infra-codepipeline' ] ]
          RoleArn: !GetAtt EwfInfraCloudWatchEventRole.Arn
          Id: CodePipelineTarget