AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - cl.aws.demo::lambda
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cl.aws.demo.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/lambda-1.0.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  LambdaApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: LambdaApi
