spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    initialization-mode: always
